version: "3.6"
services:
  postgres:
    image: postgres
    restart: unless-stopped
  mongo:
    container_name: mongo
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db